apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        imagePullPolicy: Never # Make sure it is coming from local
        image: my-backend:latest 
        ports:
        - containerPort: 8000 
        volumeMounts:
        - name: backend-data
          mountPath: /app/data 
      - name: ollama
        imagePullPolicy: Always
        image: ollama/ollama:latest
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
      volumes:
      - name: backend-data
        emptyDir: {} # Ephemeral storage for temporary data

