apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        imagePullPolicy: Never # Make sure it is coming from local
        image: my-frontend:latest # Replace with your Streamlit app image
        ports:
        - containerPort: 8501 # Streamlit default port
        volumeMounts:
        - name: streamlit-data
          mountPath: /app/data # Optional: for storing persistent data
      volumes:
      - name: streamlit-data
        emptyDir: {} # Ephemeral storage for temporary data

